### ISSUE TITLE
An error occurs when _extract_refactorings of RA-SZZ runs

### ISSUE THREAD

**Issue by Owner-MR** [grosa1/pyszz_v2#1]
![image](https://github.com/grosa1/pyszz_v2/assets/57560083/02ff19a6-7af5-4f81-ba78-28f2c037968f)

The problem seems to be that the json format of tempfile is unreadable, modified as follows:
```
def _extract_refactorings(self, commits):
        PATH_TO_REFMINER = os.path.join(Options.PYSZZ_HOME, 'tools/RefactoringMiner-2.0/bin/RefactoringMiner')

        refactorings = dict()
        for commit in commits:
            if not commit in refactorings:
                dirs = os.getcwd() + "\\temp\\"
                # with tempfile.NamedTemporaryFile(mode='r+') as tmpfile:
                log.info(f'Running RefMiner on {commit}')
                os.system(
                    PATH_TO_REFMINER + " -c " + self._repository_path + " " + commit + " > " + dirs + "tmp.json")
                with open(dirs + "tmp.json") as f:
                    refactorings[commit] = json.load(f)
                if os.path.exists(dirs + "tmp.json"):
                    os.remove(dirs + "tmp.json")
        return refactorings
```

**Comment by grosa1** [comment]
Hi! 
Thanks for opening the issues. Currently, PySZZ has been tested only on Linux-like systems (Linux and MacOS). In case you are running it on Windows, it could be a problem related to OS paths (I suppose that from the line `dirs = os.getcwd() + "\\temp\\"`).
The line `with tempfile.NamedTemporaryFile(mode='r+') as tmpfile:` delegates the management of the temporary file path to Python to avoid this kind of issue.
Please also check the permission of `PATH_TO_REFMINER `

**Comment by Owner-MR** [comment]
Thank you very much for your reply, the problem has been solved.
